/* Generated By:JavaCC: Do not edit this line. pilangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface pilangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_MAIN = 6;
  /** RegularExpression Id. */
  int END_MAIN = 7;
  /** RegularExpression Id. */
  int SEMI = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int L_BRACE = 10;
  /** RegularExpression Id. */
  int R_BRACE = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int PAR = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int L_BRA = 16;
  /** RegularExpression Id. */
  int R_BRA = 17;
  /** RegularExpression Id. */
  int LOCAL = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int R_ANG = 20;
  /** RegularExpression Id. */
  int L_ANG = 21;
  /** RegularExpression Id. */
  int IDENT_L = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int DECLARE = 25;
  /** RegularExpression Id. */
  int NUMERICO = 26;
  /** RegularExpression Id. */
  int REPL = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\\t\"",
    "\"\\t\"",
    "\"begin_main\"",
    "\"end_main\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"|\"",
    "\"=\"",
    "\"print\"",
    "\"[\"",
    "\"]\"",
    "\"local\"",
    "\"return\"",
    "\">\"",
    "\"<\"",
    "<IDENT_L>",
    "<NUMBER>",
    "\".\"",
    "\"Declare\"",
    "\"Number\"",
    "\"!\"",
  };

}
